spring:
    application:
        name: scf
    datasource:
        url: jdbc:h2:file:./data/scf
        driver-class-name: org.h2.Driver
        username: ssafy
        password: ssafy
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                web-allow-others: false
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true

logging:
    level:
        org:
            hibernate:
                SQL: debug

server:
    error:
        include-message: always
        include-binding-errors: always
