spring:
  application:
    name: scf-multi

logging:
  level:
    root: DEBUG

problem:
  server:
    url: http://www.ssafy11s.com/problem

user:
  server:
    url: http://www.ssafy11s.com/user

server:
  port: 8082
