spring:
  application:
    name: scf-chat
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: 8085
