spring:
  application:
    name: scf
  datasource:
    url: jdbc:mariadb://mariadb_db:3306/scf_db?characterEncoding=utf8mb4
    username: user
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true  # Shows SQL statements in the console
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug